definitions:
  models.Response:
    properties:
      data: {}
      jwt:
        type: string
      message:
        type: string
    type: object
  models.User:
    type: object
info:
  contact: {}
paths:
  /signup:
    post:
      consumes:
      - application/json
      description: Signs up a user, stores their details, and sends a welcome email
      parameters:
      - description: User signup details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully created
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Invalid request body or email format
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Sign up a user
      tags:
      - Auth
swagger: "2.0"
